// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkoiymsudbofumgkhwvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrb2l5bXN1ZGJvZnVtZ2tod3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTUzNTEsImV4cCI6MjA3NDY3MTM1MX0.9jsrjV16mJWG7JRT19t1KKtS-R5hG5ocfRg-h678EOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});